//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companie
    {
        public string Name { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string Description { get; set; }
    }
}
