//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.TechStack = new HashSet<TechStack>();
        }
    
        public string Name { get; set; }
        public string Plataform { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Path { get; set; }
        public string PathImages { get; set; }
        public string PathCertificated { get; set; }
    
        public virtual Plataform Plataform1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechStack> TechStack { get; set; }
    }
}
